### ISSUE TITLE
[Feature] Add Parkzer voice

### ISSUE THREAD

**Issue by HorizontalChaos** [olivertzeng/DougDougGo#1]
for example if you search for parkzer u hear a parkzer voice line (e.g "You are literally trolling.")

**Comment by olivertzeng** [comment]
hmm
alright i'll add this later i guess

**Comment by olivertzeng** [comment]
> for example if you search for parkzer u hear a parkzer voice line (e.g "You are literally trolling.")

Hmm tbh I was thinking about this

What if I really do every melee character, every gta5 words, every skyrim 
That would definitely require a damn tts which is probably impossible in js right?

**Comment by HorizontalChaos** [comment]
its up to you i guess

**Comment by olivertzeng** [comment]
> its up to you i guess
> 
> 

Hmm when do I play that voice though?
